[package]
name = "cachelane-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "cachelane"
path = "src/main.rs"

[dependencies]
base64.workspace = true
cachelane-symbols = { path = "../../crates/symbols" }
cachelane-unreal = { path = "../../crates/unreal" }
clap.workspace = true
md-5.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
flate2.workspace = true

[lints]
workspace = true
